# Generated by Django 5.2.13 on 2026-04-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='jabatan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jabatan'),
        ),
        migrations.AddField(
            model_name='user',
            name='nama',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nama Depan'),
        ),
        migrations.AddField(
            model_name='user',
            name='nama_panjang',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Belakang'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('scoring', 'Scoring'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], default='scoring', max_length=20, verbose_name='Role'),
        ),
    ]
