# Generated by Django 5.2.13 on 2026-04-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nama',
            new_name='nama_depan',
        ),
        migrations.AlterField(
            model_name='user',
            name='nama_panjang',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Panjang'),
        ),
    ]
